name: Versioned
on:
  push:
    tags:
      - "v*"

jobs:
  Release:
    name: "Release"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
